# Machine Learning for Reaserch

[Institute of Data Science at Maastricht University](https://www.maastrichtuniversity.nl/research/institute-data-science)

This notebook extends a notebook used during a machine learning workshop by the institute of data science at Maastricht University.
In order to advance my understanding of machine learning, I will try several techniques as I attempt to answer the following questions:

1. Which clusters of chronic conditions can be identified using these data?
2. Can we predict the presence of chronic illness?

The first question will be approached using *unsupervised* learning methods. The second question will be approached using *supervised* learning methods.

Several people will work on these questions independently and results will be discussed afterwards during a joint session.

## Steps to choose a method based in a research question

- 1) Get to know your data  
- 2) Fit on train data  
- 3) Evaluate on test data  
- 4) Compare Methods

In [28]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

pd.set_option("max_columns", 999)

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Load Across National Health Data
- Terms of use [ICPSR 34241](https://www.icpsr.umich.edu/icpsrweb/ICPSR/studies/34241/terms)

This Across-national Health Outcome dataset includes over 30000 participants' personal social, economic, life-style, health data across 6 countries -- India, Ghana, China, South Africa, Mexico, and Russia. Features contains income, education level, parents socio-economic level, drinking, smoking, self-report health status, chronic disease, etc.
Dataset contains categorial value: 0 or 1 or -1 (-1 means value is missing), numercial values.

This data is a part of Research on Early Life and Aging Trends and Effects:
McEniry, Mary. Research on Early Life and Aging Trends and Effects (RELATE): A Cross-National Study. Ann Arbor, MI: Inter-university Consortium for Political and Social Research [distributor], 2015-05-07. https://doi.org/10.3886/ICPSR34241.v2

In [4]:
output = "../data/across-national-health-data.csv"

if not os.path.exists(output):
    df = (pd.read_csv('https://s3.eu-west-3.amazonaws.com/pedrohserrano-datasets/across-national-health-data.csv')
         .rename(columns=str.lower))
    df.to_csv(output, index=False)
else:
    df = (pd.read_csv(output)
          .rename(columns=str.lower))

df = df.set_index("id")

In [5]:
df.head()

,country,birthcohort,residence,gender,age,civil,positionfin,yeduca,education,income,ppp,quint,wealth_index,wealth_assets,hhsize,hscore,regime,ruralfin,birthmonth,birthyear,mothereduc_gen,motheroccup_sage,height,height25new,stunt,fathereduc_gen,fatheroccup_sage,smoke,smoke_gen,exercise,exercise_rigor,drink,healthuse,health_sage,poorhealth,goodhealth,nadlgt0,nadlgt0_alt,niadlgt0,nadlgt0harm,bath,dress,toilet,transfer,bow,hypertension,respiratory,heart,angina,heart_attack,diabetes,stroke,arthritis,nchronic,weight,waist,hip,bmi,bmi_cat,obesity
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3323,Ghana-WHO/SAGE,15,0,1,50,2,1,0,2,,,-1,2,3,6,135,5,0,3,1957,1,3,172.4,0,0,1,3,0,0,1,1,1,0,2,0,83.3333,0,1,0,0,0,0,0,0,1,0,0,0,0,-1,0,0,0,0,76,104,106,25.57049,4,0
11580,China-WHO/SAGE,12,0,1,66,1,1,2,2,20000,8294.836,5,3,7,2,144,5,1,1,1941,1,5,163,0,0,1,5,0,0,0,0,0,1,4,1,66.6667,0,1,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,1,1,65.5,88,100,24.65279,3,0
5593,China-WHO/SAGE,12,1,1,65,1,3,0,1,2333.333,967.7308,2,1,1,3,144,5,1,7,1942,1,3,136.2,1,1,1,3,0,0,0,0,0,1,4,1,50,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,32,64.2,84.4,17.25027,2,0
8744,China-WHO/SAGE,12,0,0,68,1,2,6,2,30000,12442.25,5,3,7,2,144,5,0,10,1942,1,5,166,0,0,2,5,0,0,0,0,1,0,2,0,83.3333,0,1,0,0,0,0,0,0,0,0,0,-1,-1,-1,0,0,0,0,75,95,102,27.2173,4,0
6277,China-WHO/SAGE,14,1,0,55,1,1,6,2,5000,2073.709,3,3,6,2,144,5,1,2,1952,1,3,170.8,0,0,1,3,1,2,0,0,0,1,3,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,69,76.5,90.5,23.6523,3,0

---
## Get to know your data

The user guide can be found as pdf in "../34241-User_guide.pdf"

In [6]:
# a look at the numeric variables
df.describe()

,birthcohort,residence,gender,civil,positionfin,education,quint,wealth_index,wealth_assets,hscore,regime,ruralfin,birthmonth,birthyear,mothereduc_gen,motheroccup_sage,height25new,stunt,fathereduc_gen,fatheroccup_sage,smoke,smoke_gen,exercise,exercise_rigor,drink,healthuse,health_sage,poorhealth,nadlgt0,nadlgt0_alt,niadlgt0,nadlgt0harm,bath,dress,toilet,transfer,bow,hypertension,respiratory,heart,angina,heart_attack,diabetes,stroke,arthritis,nchronic,bmi_cat,obesity
count,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.0,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000
mean,11.315176,0.445169,0.434964,1.619404,1.323605,1.796978,2.307462,2.204665,3.995679,129.168297,4.567581,0.352419,3.973360,1809.558224,0.924983,3.010073,0.066799,-0.098661,1.064944,2.337124,0.201087,0.443101,0.116024,0.116024,0.207237,0.239496,2.438887,0.066137,0.029874,0.257734,0.088535,0.013810,-0.062425,-0.069344,-0.055136,-0.018635,0.099934,0.128774,-0.055162,-0.133121,-0.133121,-1.0,-0.047634,-0.084904,0.071146,0.554672,2.719841,-0.029264
std,3.868191,0.558426,0.620141,1.500357,0.891373,1.385564,1.975064,1.077217,2.836785,29.353722,0.669696,0.706874,4.515658,493.609185,1.040324,2.042169,0.604644,0.441606,1.226787,1.820011,0.629282,0.982930,0.579927,0.579927,0.633633,0.828899,1.438599,0.534713,0.521140,0.725957,0.635814,0.498003,0.403305,0.391180,0.413474,0.456341,0.568247,0.592347,0.418219,0.604201,0.604201,0.0,0.428834,0.374792,0.545974,1.094957,1.813441,0.525959
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,61.000000,3.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-8.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,10.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,112.000000,4.000000,0.000000,-1.000000,1935.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.0,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000
50%,12.000000,0.000000,1.000000,1.000000,1.000000,2.000000,2.000000,3.000000,4.000000,135.000000,5.000000,0.000000,3.000000,1945.000000,1.000000,3.000000,0.000000,0.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.0,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000
75%,14.000000,1.000000,1.000000,2.000000,2.000000,3.000000,4.000000,3.000000,7.000000,144.000000,5.000000,1.000000,8.000000,1952.000000,1.000000,5.000000,0.000000,0.000000,2.000000,3.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.0,0.000000,0.000000,0.000000,1.000000,4.000000,0.000000
max,16.000000,1.000000,1.000000,5.000000,3.000000,4.000000,5.000000,3.000000,8.000000,175.000000,5.000000,1.000000,12.000000,1978.000000,4.000000,5.000000,1.000000,1.000000,4.000000,5.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-1.0,1.000000,1.000000,1.000000,6.000000,5.000000,1.000000

In [7]:
# what about categorical variables?
df.select_dtypes(include=[object]).head()

,country,age,yeduca,income,ppp,hhsize,height,goodhealth,weight,waist,hip,bmi
id,,,,,,,,,,,,
3323,Ghana-WHO/SAGE,50,0,,,6,172.4,83.3333,76,104,106,25.57049
11580,China-WHO/SAGE,66,2,20000,8294.836,2,163,66.6667,65.5,88,100,24.65279
5593,China-WHO/SAGE,65,0,2333.333,967.7308,3,136.2,50,32,64.2,84.4,17.25027
8744,China-WHO/SAGE,68,6,30000,12442.25,2,166,83.3333,75,95,102,27.2173
6277,China-WHO/SAGE,55,6,5000,2073.709,2,170.8,100,69,76.5,90.5,23.6523

In [8]:
# looks like those should alse be numerical, except for country
categorical_vars = df.select_dtypes(include=[object]).columns.tolist()
categorical_vars.remove("country")

for catvar in categorical_vars:
    df[catvar] = pd.to_numeric(df[catvar], errors="coerce")

df.loc[:, categorical_vars].dtypes
df.loc[:, categorical_vars].head()

,age,yeduca,income,ppp,hhsize,height,goodhealth,weight,waist,hip,bmi
id,,,,,,,,,,,
3323,50.0,0.0,NaN,NaN,6.0,172.4,83.3333,76.0,104.0,106.0,25.57049
11580,66.0,2.0,20000.000,8294.8360,2.0,163.0,66.6667,65.5,88.0,100.0,24.65279
5593,65.0,0.0,2333.333,967.7308,3.0,136.2,50.0000,32.0,64.2,84.4,17.25027
8744,68.0,6.0,30000.000,12442.2500,2.0,166.0,83.3333,75.0,95.0,102.0,27.21730
6277,55.0,6.0,5000.000,2073.7090,2.0,170.8,100.0000,69.0,76.5,90.5,23.65230

In [9]:
# now let's look at ALL numeric variables
df.describe()

,birthcohort,residence,gender,age,civil,positionfin,yeduca,education,income,ppp,quint,wealth_index,wealth_assets,hhsize,hscore,regime,ruralfin,birthmonth,birthyear,mothereduc_gen,motheroccup_sage,height,height25new,stunt,fathereduc_gen,fatheroccup_sage,smoke,smoke_gen,exercise,exercise_rigor,drink,healthuse,health_sage,poorhealth,goodhealth,nadlgt0,nadlgt0_alt,niadlgt0,nadlgt0harm,bath,dress,toilet,transfer,bow,hypertension,respiratory,heart,angina,heart_attack,diabetes,stroke,arthritis,nchronic,weight,waist,hip,bmi,bmi_cat,obesity
count,37725.000000,37725.000000,37725.000000,35116.000000,37725.000000,37725.000000,33197.000000,37725.000000,3.131700e+04,31317.000000,37725.000000,37725.000000,37725.000000,36226.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,32005.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,33494.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.000000,37725.0,37725.000000,37725.000000,37725.000000,37725.000000,32070.000000,31540.000000,31484.000000,31939.000000,37725.000000,37725.000000
mean,11.315176,0.445169,0.434964,63.550148,1.619404,1.323605,5.521342,1.796978,1.498901e+05,3181.859343,2.307462,2.204665,3.995679,4.125573,129.168297,4.567581,0.352419,3.973360,1809.558224,0.924983,3.010073,159.116322,0.066799,-0.098661,1.064944,2.337124,0.201087,0.443101,0.116024,0.116024,0.207237,0.239496,2.438887,0.066137,78.592183,0.029874,0.257734,0.088535,0.013810,-0.062425,-0.069344,-0.055136,-0.018635,0.099934,0.128774,-0.055162,-0.133121,-0.133121,-1.0,-0.047634,-0.084904,0.071146,0.554672,62.671690,86.380489,95.373565,24.810260,2.719841,-0.029264
std,3.868191,0.558426,0.620141,9.800265,1.500357,0.891373,5.074384,1.385564,6.298205e+06,9588.530207,1.975064,1.077217,2.836785,2.996394,29.353722,0.669696,0.706874,4.515658,493.609185,1.040324,2.042169,9.970561,0.604644,0.441606,1.226787,1.820011,0.629282,0.982930,0.579927,0.579927,0.633633,0.828899,1.438599,0.534713,22.761310,0.521140,0.725957,0.635814,0.498003,0.403305,0.391180,0.413474,0.456341,0.568247,0.592347,0.418219,0.604201,0.604201,0.0,0.428834,0.374792,0.545974,1.094957,16.591431,14.361140,14.091154,7.344935,1.813441,0.525959
min,-1.000000,-1.000000,-1.000000,29.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000e+00,0.000000,-1.000000,-1.000000,-1.000000,1.000000,61.000000,3.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,80.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-8.000000,-1.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.000000,-1.000000,-1.000000,-1.000000,24.000000,25.000000,-8.000000,8.018978,-1.000000,-1.000000
25%,10.000000,0.000000,0.000000,55.000000,1.000000,1.000000,0.000000,1.000000,2.500000e+03,567.312900,1.000000,1.000000,1.000000,2.000000,112.000000,4.000000,0.000000,-1.000000,1935.000000,1.000000,1.000000,153.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,2.000000,0.000000,66.666700,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.0,0.000000,0.000000,0.000000,0.000000,51.000000,77.375000,87.300000,20.683710,3.000000,0.000000
50%,12.000000,0.000000,1.000000,62.000000,1.000000,1.000000,5.000000,2.000000,6.666667e+03,1410.122000,2.000000,3.000000,4.000000,3.000000,135.000000,5.000000,0.000000,3.000000,1945.000000,1.000000,3.000000,159.200000,0.000000,0.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,83.333300,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.0,0.000000,0.000000,0.000000,0.000000,60.500000,85.200000,94.500000,23.762650,3.000000,0.000000
75%,14.000000,1.000000,1.000000,70.000000,2.000000,2.000000,9.000000,3.000000,1.800000e+04,3403.877000,4.000000,3.000000,7.000000,5.000000,144.000000,5.000000,1.000000,8.000000,1952.000000,1.000000,5.000000,165.800000,0.000000,0.000000,2.000000,3.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,3.000000,0.000000,100.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.0,0.000000,0.000000,0.000000,1.000000,71.200000,94.300000,102.000000,27.398460,4.000000,0.000000
max,16.000000,1.000000,1.000000,114.000000,5.000000,3.000000,26.000000,4.000000,4.600000e+08,752030.700000,5.000000,3.000000,8.000000,40.000000,175.000000,5.000000,1.000000,12.000000,1978.000000,4.000000,5.000000,228.000000,1.000000,1.000000,4.000000,5.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,5.000000,1.000000,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-1.0,1.000000,1.000000,1.000000,6.000000,200.000000,227.000000,400.000000,239.531300,5.000000,1.000000

### How many features are there ?

In [10]:
# rows and features/columns
df.shape

(37725, 60)

### Is any value missing in the dataset ?

In [11]:
def show_missing_values(df):
    
    # overview of missing values per variable
    ismiss = df.isnull().sum()
    
    # the sum of that is the total of missing values
    print("Total missing values: {}".format(ismiss.sum()))
    
    # have a closer look only if the total of missing values is not zero
    if ismiss.sum() > 0:
        missdf = pd.DataFrame(ismiss[ismiss > 0], index=(ismiss[ismiss > 0].index), columns=["missing_values"])
        missdf["missing_values_as_perc"] = round(missdf["missing_values"] / df.shape[0] * 100, 1)
        print(missdf)

In [12]:
# set -1 to NaN
df = df[df != -1]
show_missing_values(df)

Total missing values: 315364
                  missing_values  missing_values_as_perc
birthcohort                 2609                     6.9
residence                   1223                     3.2
gender                      2618                     6.9
age                         2609                     6.9
civil                       2819                     7.5
positionfin                 2283                     6.1
yeduca                      4528                    12.0
education                   4528                    12.0
income                      6408                    17.0
ppp                         6408                    17.0
quint                       6408                    17.0
wealth_index                1792                     4.8
wealth_assets               1792                     4.8
hhsize                      1499                     4.0
ruralfin                    5120                    13.6
birthmonth                 12606                    33.4
birthyear                   2609                     6.9
mothereduc_gen              6277                    16.6
motheroccup_sage            4926                    13.1
height                      5720                    15.2
height25new                 5720                    15.2
stunt                       5723                    15.2
fathereduc_gen              7151                    19.0
fatheroccup_sage            5260                    13.9
smoke                       4439                    11.8
smoke_gen                   4439                    11.8
exercise                    4409                    11.7
exercise_rigor              4409                    11.7
drink                       4474                    11.9
healthuse                   9524                    25.2
health_sage                 4227                    11.2
poorhealth                  4228                    11.2
goodhealth                  4231                    11.2
nadlgt0                     4576                    12.1
nadlgt0_alt                 6332                    16.8
niadlgt0                    6103                    16.2
nadlgt0harm                 4421                    11.7
bath                        4319                    11.4
dress                       4285                    11.4
toilet                      4322                    11.5
transfer                    4286                    11.4
bow                         4394                    11.6
hypertension                4502                    11.9
respiratory                 4397                    11.7
heart                       9731                    25.8
angina                      9731                    25.8
heart_attack               37725                   100.0
diabetes                    4410                    11.7
stroke                      4387                    11.6
arthritis                   4376                    11.6
nchronic                    4612                    12.2
weight                      5655                    15.0
waist                       6185                    16.4
hip                         6241                    16.5
bmi                         5786                    15.3
bmi_cat                     5786                    15.3
obesity                     5786                    15.3

# Data prep/cleanup/wrangling

## Entire dataset

In [13]:
# heart_attach has 100% missing, let's get rid of it
del df["heart_attack"]

In [14]:
# create binary variable to indicate chronic illness
df["ischronic"] = df["nchronic"] >= 1

# how many people are chronically ill?
df.ischronic.value_counts()

False    21779
True     15946
Name: ischronic, dtype: int64

In [15]:
# save a copy without missing values and clear country values for Tableau workshop
print(df.shape)
dfnonan = df.dropna()
print(dfnonan.shape)
dfnonan["country"] = dfnonan.country.str.split("-").str[0]
dfnonan_unique = dfnonan.groupby("id").last()
print(dfnonan_unique.shape)
print(set(dfnonan.country))

(37725, 60)
(10951, 60)
(7787, 60)
{'India', 'Russia', 'Ghana', 'Mexico', 'South Africa', 'China'}

C:\Users\niels.hameleers\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [16]:
dfnonan_unique.head()

,country,birthcohort,residence,gender,age,civil,positionfin,yeduca,education,income,ppp,quint,wealth_index,wealth_assets,hhsize,hscore,regime,ruralfin,birthmonth,birthyear,mothereduc_gen,motheroccup_sage,height,height25new,stunt,fathereduc_gen,fatheroccup_sage,smoke,smoke_gen,exercise,exercise_rigor,drink,healthuse,health_sage,poorhealth,goodhealth,nadlgt0,nadlgt0_alt,niadlgt0,nadlgt0harm,bath,dress,toilet,transfer,bow,hypertension,respiratory,heart,angina,diabetes,stroke,arthritis,nchronic,weight,waist,hip,bmi,bmi_cat,obesity,ischronic
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,Mexico,11.0,0.0,1.0,72.0,1.0,2.0,9.0,3.0,12000.00,1361.551000,4.0,3.0,5.0,4.0,61,4,0.0,6.0,1937.0,4.0,1.0,148.3,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,66.6667,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,78.2,83.3,138.5,35.55694,5.0,1.0,True
2,Russia,13.0,0.0,1.0,61.0,4.0,1.0,7.0,3.0,21333.33,857.252700,1.0,3.0,8.0,3.0,130,4,0.0,8.0,1946.0,2.0,1.0,158.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,3.0,0.0,66.6667,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,2.0,82.0,109.0,124.5,32.84730,5.0,1.0,True
3,China,12.0,1.0,1.0,63.0,1.0,2.0,6.0,2.0,5000.00,2073.709000,3.0,2.0,3.0,6.0,144,5,1.0,3.0,1945.0,2.0,5.0,155.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,100.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55.0,75.2,96.0,22.89282,3.0,0.0,False
4,India,13.0,1.0,0.0,58.0,1.0,3.0,9.0,3.0,33000.00,2954.406000,5.0,3.0,5.0,4.0,112,5,1.0,3.0,1949.0,1.0,5.0,175.1,0.0,0.0,2.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,100.0000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,57.0,82.0,89.0,18.59099,3.0,0.0,False
5,China,13.0,1.0,1.0,61.0,1.0,2.0,3.0,2.0,1.00,0.414742,1.0,2.0,3.0,5.0,144,5,1.0,11.0,1947.0,1.0,5.0,144.0,1.0,0.0,1.0,5.0,0.0,0.0,1.0,1.0,0.0,1.0,4.0,1.0,66.6667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,40.0,76.0,86.0,19.29012,3.0,0.0,True

In [17]:
dfnonan_unique.to_csv("C:/Users/niels.hameleers/Desktop/across-national-health-data-no-missing.csv")

## Subset for Question 1

In [18]:
# use a subset of the data for this question, only containing the conditions
conditions = ["hypertension",
              "respiratory",
              "heart",
              "angina",
              "diabetes",
              "stroke",
              "arthritis"]

clust = df.loc[:, conditions]

In [19]:
clust.head()

       hypertension  respiratory  heart  angina  diabetes  stroke  arthritis
id
3323            0.0          0.0    0.0     0.0       0.0     0.0        0.0
11580           0.0          0.0    0.0     0.0       0.0     0.0        1.0
5593            0.0          0.0    0.0     0.0       0.0     0.0        0.0
8744            0.0          0.0    NaN     NaN       0.0     0.0        0.0
6277            0.0          0.0    0.0     0.0       0.0     0.0        0.0

In [20]:
# dimensions
clust.shape

(37725, 7)

In [21]:
# how about missing values?
show_missing_values(clust)

Total missing values: 41534
              missing_values  missing_values_as_perc
hypertension            4502                    11.9
respiratory             4397                    11.7
heart                   9731                    25.8
angina                  9731                    25.8
diabetes                4410                    11.7
stroke                  4387                    11.6
arthritis               4376                    11.6

In [22]:
# it's quite rigorous, but let's remove all rows with any missing values
clust = clust.dropna()
# dimensions after removing those rows
clust.shape

(27832, 7)

# Question 1: Which clusters of chronic conditions can be identified using these data?

## Approach 1: Clustering

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
# let's run Kmeans a few times creating different numbers of clusters
nr_of_clusters = range(2,7)

clust_results = clust.copy()

for n in nr_of_clusters:
    # run Kmeans with n clusters
    km = KMeans(n_clusters=n, random_state=0, n_init=100, max_iter=10000, n_jobs = -2).fit(clust)
    # save the labels in the results dataframe
    clust_results["kmeans_nclust{}_labels".format(n)] = km.labels_

In [ ]:
clust_results.head()

In [ ]:
# how's the distribution of patients for each run?
for n in nr_of_clusters:
    clust_results["kmeans_nclust{}_labels".format(n)].hist()
    plt.show()

Looks like there is always one predominant cluster with many people. Perhaps those who are not chronically ill?

In [ ]:
# let's check first on one example before implementing the loop
colname = "kmeans_nclust5_labels"
c = 0
# clust_results.loc[clust_results[colname] == c, conditions].plot(kind="bar")

In [ ]:
# # For each run (nr_of_clusters)
#     # for each class
#         # show the distribution of chronic conditions
        
# for n in nr_of_clusters:
    
#     print("Plotting for {} clusters:".format(n))

#     colname = "kmeans_nclust{}_labels".format(n)
        
#     for c in range(n):
#         print("Showing barchart for class: {}".format(c))
#         clust_results.loc[clust_results[colname], conditions].plot(kind="bar")
#         plt.show()

# Predicting whether someone is chronically ill

In [52]:
df.head()

,country,birthcohort,residence,gender,age,civil,positionfin,yeduca,education,income,ppp,quint,wealth_index,wealth_assets,hhsize,hscore,regime,ruralfin,birthmonth,birthyear,mothereduc_gen,motheroccup_sage,height,height25new,stunt,fathereduc_gen,fatheroccup_sage,smoke,smoke_gen,exercise,exercise_rigor,drink,healthuse,health_sage,poorhealth,goodhealth,nadlgt0,nadlgt0_alt,niadlgt0,nadlgt0harm,bath,dress,toilet,transfer,bow,hypertension,respiratory,heart,angina,diabetes,stroke,arthritis,nchronic,weight,waist,hip,bmi,bmi_cat,obesity,ischronic
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3323,Ghana-WHO/SAGE,15.0,0.0,1.0,50.0,2.0,1.0,0.0,2.0,NaN,NaN,NaN,2.0,3.0,6.0,135,5,0.0,3.0,1957.0,1.0,3.0,172.4,0.0,0.0,1.0,3.0,0.0,0.0,1.0,1.0,1.0,0.0,2.0,0.0,83.3333,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,76.0,104.0,106.0,25.57049,4.0,0.0,False
11580,China-WHO/SAGE,12.0,0.0,1.0,66.0,1.0,1.0,2.0,2.0,20000.000,8294.8360,5.0,3.0,7.0,2.0,144,5,1.0,1.0,1941.0,1.0,5.0,163.0,0.0,0.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,1.0,66.6667,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,65.5,88.0,100.0,24.65279,3.0,0.0,True
5593,China-WHO/SAGE,12.0,1.0,1.0,65.0,1.0,3.0,0.0,1.0,2333.333,967.7308,2.0,1.0,1.0,3.0,144,5,1.0,7.0,1942.0,1.0,3.0,136.2,1.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,1.0,50.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,64.2,84.4,17.25027,2.0,0.0,False
8744,China-WHO/SAGE,12.0,0.0,0.0,68.0,1.0,2.0,6.0,2.0,30000.000,12442.2500,5.0,3.0,7.0,2.0,144,5,0.0,10.0,1942.0,1.0,5.0,166.0,0.0,0.0,2.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,83.3333,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,75.0,95.0,102.0,27.21730,4.0,0.0,False
6277,China-WHO/SAGE,14.0,1.0,0.0,55.0,1.0,1.0,6.0,2.0,5000.000,2073.7090,3.0,3.0,6.0,2.0,144,5,1.0,2.0,1952.0,1.0,3.0,170.8,0.0,0.0,1.0,3.0,1.0,2.0,0.0,0.0,0.0,1.0,3.0,0.0,100.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69.0,76.5,90.5,23.65230,3.0,0.0,False

In [53]:
df.columns

Index(['country', 'birthcohort', 'residence', 'gender', 'age', 'civil',
       'positionfin', 'yeduca', 'education', 'income', 'ppp', 'quint',
       'wealth_index', 'wealth_assets', 'hhsize', 'hscore', 'regime',
       'ruralfin', 'birthmonth', 'birthyear', 'mothereduc_gen',
       'motheroccup_sage', 'height', 'height25new', 'stunt', 'fathereduc_gen',
       'fatheroccup_sage', 'smoke', 'smoke_gen', 'exercise', 'exercise_rigor',
       'drink', 'healthuse', 'health_sage', 'poorhealth', 'goodhealth',
       'nadlgt0', 'nadlgt0_alt', 'niadlgt0', 'nadlgt0harm', 'bath', 'dress',
       'toilet', 'transfer', 'bow', 'hypertension', 'respiratory', 'heart',
       'angina', 'diabetes', 'stroke', 'arthritis', 'nchronic', 'weight',
       'waist', 'hip', 'bmi', 'bmi_cat', 'obesity', 'ischronic'],
      dtype='object')

In [90]:
predictors = ["gender", "age", "education", "ppp", "mothereduc_gen", "fathereduc_gen", 
              "bmi", "smoke", "exercise", "drink"]
outcome = "ischronic"

In [91]:
# for the sake of this exercise, simply remove all rows with missing
df.shape
df_no_nan = df.dropna()
df_no_nan.shape

(37725, 60)

(10951, 60)

In [92]:
X = df_no_nan.loc[:, predictors]
y = df_no_nan.loc[:, outcome]

In [93]:
X.shape
y.shape

(10951, 10)

(10951,)

In [94]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [95]:
X_train.shape
y_train.shape

X_test.shape
y_test.shape

(8760, 10)

(8760,)

(2191, 10)

(2191,)

## Let's try a few classifiers without tuning parameters

In [96]:
from sklearn.dummy import DummyClassifier

dummy_clf = DummyClassifier()
dummy_clf = dummy_clf.fit(X_train, y_train)
y_pred = dummy_clf.predict(X_test)

accuracy_score(y_test, y_pred)

0.50342309447740763

In [109]:
from sklearn import tree

tree_clf = tree.DecisionTreeClassifier(min_samples_split=100, min_samples_leaf=50)
tree_clf = tree_clf.fit(X_train, y_train)
y_pred = tree_clf.predict(X_test)

tree_clf.score(X_test, y_test)

0.62665449566408038

In [110]:
from sklearn.model_selection import cross_val_score

cross_val_score(tree_clf, X, y, cv=5, n_jobs=3, verbose=1)

[Parallel(n_jobs=3)]: Done   5 out of   5 | elapsed:   10.4s finished

array([ 0.62254678,  0.62026472,  0.62254678,  0.62448607,  0.62265875])

In [101]:
import graphviz

dot_data = tree.export_graphviz(tree_clf, out_file=None,
                                max_depth=4,
                               feature_names=X.columns,
                               class_names=["NOT chronically ill", "Chronically ill"],
                               filled=True) 
graph = graphviz.Source(dot_data) 
graph.render("tree")

'tree.pdf'

In [87]:
tree.export_graphviz?

### Logistic regression

In [107]:
from sklearn.linear_model import LogisticRegression

log_clf = LogisticRegression()
log_clf = log_clf.fit(X_train, y_train)
y_pred_log = log_clf.predict(X_test)

log_clf.score(X_test, y_test)

0.63441350981287081

0.63441350981287081

### Neural net with sklearn

In [116]:
from sklearn.neural_network import MLPClassifier
nn_clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                     hidden_layer_sizes=(5, 2), random_state=1)
nn_clf = nn_clf.fit(X_train, y_train)                         
y_pred_nn = nn_clf.predict(X_test)

nn_clf.score(X_test, y_test)

0.52806937471474213

---
## Fit on train data

---
## Evaluate on test data

---
### Documentation of the Method

The goal of construct a method is the reproducibility, that is why is important to document the procedures, taking into account versioning control of script for replicable science.

Notebooks like this one go a long way toward making our work reproducible. Since we documented every step as we moved along, we have a written record of what we did and why we did it — both in text and code.

Beyond recording what we did, we should also document what software and hardware we used to perform our analysis. This typically goes at the top of our notebooks so our readers know what tools to use.

[Sebastian Raschka](https://sebastianraschka.com/) created a handy notebook tool for this:

In [ ]:
#!pip install watermark
#only install once

In [ ]:
%load_ext watermark

In [ ]:
%watermark -a 'Maastricht University' -nmv --packages turicreate,pandas,seaborn,matplotlib